service: earthdata-search

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  endpointType: PRIVATE
  memorySize: 128
  environment:
    # Variables for new Encrypted database
    databaseEndpoint:
      Fn::ImportValue: ${self:provider.stage}-EncryptedDatabaseEndpoint
    databasePort:
      Fn::ImportValue: ${self:provider.stage}-EncryptedDatabasePort

    dbUsername: edsc
    dbName: edsc_${self:provider.stage}

    colorMapQueueUrl:
      Ref: ColorMapsProcessingQueue
    tagQueueUrl:
      Ref: TagProcessingQueue
    cmrOrderingOrderQueueUrl:
      Ref: CmrOrderingOrderQueue
    catalogRestQueueUrl:
      Ref: CatalogRestOrderQueue
    harmonyQueueUrl:
      Ref: HarmonyOrderQueue
    userDataQueueUrl:
      Ref: UserDataQueue

    obfuscationSpin: ${self:custom.variables.obfuscationSpin}
    obfuscationSpinShapefiles: ${self:custom.variables.obfuscationSpinShapefiles}

    orderDelaySeconds: ${self:custom.variables.orderDelaySeconds}

    configSecretId:
      Fn::ImportValue: ${self:provider.stage}-DbPasswordSecret

    collectionCapabilitiesLambda: ${self:custom.siteName}-generateCollectionCapabilityTags

    NODE_OPTIONS: '--enable-source-maps'

  vpc:
    securityGroupIds:
      - Fn::ImportValue: ${self:provider.stage}-LambdaSecurityGroup
    subnetIds:
      - ${env:SUBNET_ID_A, 'subnetIdA'}
      - ${env:SUBNET_ID_B, 'subnetIdB'}

  iam:
    role:
      Fn::ImportValue: ${self:provider.stage}-EDSCServerlessAppRole

  # Prevent Serverless from attempting to modify the deployment bucket policy as NGAP does not allow it
  deploymentBucket:
    skipPolicySetup: true

  # Deprecation warning: Starting with next major version, API Gateway naming will be changed from "{stage}-{service}" to "{service}-{stage}".
  # Set "provider.apiGateway.shouldStartNameWithService" to "true" to adapt to the new behavior now.
  # More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-finch
  - serverless-webpack
  - serverless-step-functions
  - serverless-plugin-split-stacks
  - serverless-plugin-log-subscription
  - serverless-plugin-ifelse
  - serverless-offline
  - ./serverless-plugins/serverless-webpack-include-migrations.js

#
# Lambda Functions
#
functions: ${file(./serverless-configs/${self:provider.name}-functions.yml)}

#
# Additional AWS Resources
#
resources: ${file(./serverless-configs/${self:provider.name}-resources.yml)}

#
# Step functions to manage order status jobs
#
stepFunctions: ${file(./serverless-configs/${self:provider.name}-step-functions.yml)}

# Package each lambda into individual zip files. This reduces the size of
# each lambda but increases the complexity of the compilation process slightly
package:
  individually: true

configValidationMode: error

custom:
  siteName: earthdata-search-${self:provider.stage}

  infrastructureStackName: earthdata-search-infrastructure-${self:provider.stage}

  serverlessIfElse:
    # When invoking an offline lambda with `npm run invoke-local` this condition will disable serverless components that need to import or reference cloudformation values
    - If: '"${self:provider.stage}" == "invokeLocal"'
      Exclude:
        - provider.environment.databaseEndpoint
        - provider.environment.databasePort
        - provider.environment.colorMapQueueUrl
        - provider.environment.tagQueueUrl
        - provider.environment.cmrOrderingOrderQueueUrl
        - provider.environment.catalogRestQueueUrl
        - provider.environment.harmonyQueueUrl
        - provider.environment.userDataQueueUrl
        - provider.environment.configSecretId
        - provider.vpc
        - provider.iam
        - functions.submitCatalogRestOrder.environment.updateOrderStatusStateMachineArn
        - functions.submitCmrOrderingOrder.environment.updateOrderStatusStateMachineArn
        - functions.submitHarmonyOrder.environment.updateOrderStatusStateMachineArn

  variables:
    # Default values for environment variables used to set environment variables
    obfuscationSpin: ${env:OBFUSCATION_SPIN, ''}
    obfuscationSpinShapefiles: ${env:OBFUSCATION_SPIN_SHAPEFILES, ''}
    orderDelaySeconds: ${env:ORDER_DELAY_SECONDS, '1'}

    cloudfrontToCloudwatchBucketPrefixApi:
      Fn::Join:
        - '/'
        - - 'cloudfront/AWSLogs'
          - !Ref 'AWS::AccountId'
          - ${self:provider.region}
          - 'search_${self:provider.stage}_api/'
    cloudfrontToCloudwatchBucketPrefixS3:
      Fn::Join:
        - '/'
        - - 'cloudfront/AWSLogs'
          - !Ref 'AWS::AccountId'
          - ${self:provider.region}
          - 'search_${self:provider.stage}_s3/'

  # Finch (S3 sync plugin)
  client:
    bucketName: ${self:custom.siteName}
    distributionFolder: static/dist
    objectHeaders:
      index.html:
        - name: Cache-Control
          value: no-store
      '*.css':
        - name: Cache-Control
          value: 'max-age=31536000'
      '*.js':
        - name: Cache-Control
          value: 'max-age=31536000'
      assets/:
        - name: Cache-Control
          value: 'max-age=31536000'

    # Prevent the plugin from attempting to change the bucket policy
    manageResources: false

  # Default is 3000 so to avoid conflicts with rails applications we'll define a new port
  serverless-offline:
    httpPort: 3001
    reloadHandler: true
    # Uncomment useInProcess to enable in-process run mode
    # https://github.com/dherault/serverless-offline#run-modes
    # useInProcess: true

  # Serverless Webpack configurations
  webpack:
    webpackConfig: 'serverless.webpack.config.js'
    includeModules:
      forceExclude:
        - aws-sdk
    packager: 'npm'
    excludeFiles: src/**/*.test.js

  # Manage resource count (Maximum of 200) by splitting up the cloudformation templates
  splitStacks:
    perFunction: true

  logSubscription:
    enabled: true
    destinationArn: ${env:LOG_DESTINATION_ARN, ''}
